services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb
    networks:
      - clbb

  # connection-example:
  #   container_name: connection-example
  #   build: ./connection-example
  #   restart: always
  #   ports:
  #     - "1234:1234"
  #   volumes:
  #     - ./connection-example:/app
  #   # networks:
  #     # - clbb

volumes:
  mongo_data:
  mongo_config:

networks:
  clbb:
    external: true